
name: 'iloc_metabase'
version: '0.1.0'
require-dbt-version: ['>=1.3.0']
config-version: 2
profile: 'iloc_metabase'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  iloc_metabase:
    +materialized: table

vars:
  metabase_database: "dbt-iloc"
  metabase_schema: "metabase"
  metabase_target_tz: "UTC"
  metabase_source_tz: "UTC"